# auto-generated by nosebug (https://github.com/kmanley/nosebug.git)
import cgi
import StringIO
html_escape = cgi.escape
    
def get_ctx_value(stack, path):
    # current context is at stack[-1]
    parts = path.split("/")
    idx = -1
    curr = stack[idx]
    for part in parts:
        # Note: the parser ensures the path is well-formed
        if part == "..":
            idx -= 1
            curr = stack[idx]
        else:
            curr = curr.get(part)
    return curr

def start_section(stack, path):
    temp = get_ctx_value(stack, path) or []
    try:
        iter(temp)
    except TypeError:
        temp = [temp]
    return temp
 
def iter_test2(d):
    o = StringIO.StringIO()
    stack = [d]
    yield 'Here is a list of all the repos:\n<ul>\n'
    for _ in start_section(stack, 'repo'):
        if type(_) == dict:
            stack.append(_)
        yield '\n  <li><b>'
        yield html_escape(unicode(get_ctx_value(stack, 'name')))
        yield '</b></li>\n'
        stack.pop()
    yield '\n</ul>\n\n'
    
def test2(d): 
    o = StringIO.StringIO()
    for chunk in iter_test2(d):
        o.write(chunk)
    return o.getvalue()

